export const LOAD_STATS = 'LOAD_STATS';
export const LOAD_GLOBAL_STATS = 'LOAD_GLOBAL_STATS';
export const SET_PINNED_COUNTRY = 'SET_PINNED_COUNTRY';
export const CLEAR_PINNED_COUNTRY = 'CLEAR_PINNED_COUNTRY';
export const SET_LAST_UPDATED = 'SET_LAST_UPDATED';
export const SET_SETTING = 'SET_SETTING';